export const countries = [
    "India",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

export const technologies = [
    "AWS",
    "Angular",
    "Assembly",
    "Atom",
    "Azure",
    "Bash",
    "Bootstrap",
    "C",
    "C#",
    "C++",
    "COBOL",
    "CSS",
    "Clojure",
    "Dart",
    "Django",
    "Docker",
    "Eclipse",
    "Elixir",
    "Elm",
    "Erlang",
    "Express.js",
    "F#",
    "Firebase",
    "Flask",
    "Fortran",
    "Git",
    "Go",
    "Google Cloud Platform",
    "GraphQL",
    "Groovy",
    "HTML",
    "Haskell",
    "IntelliJ IDEA",
    "Java",
    "JavaScript",
    "Jira",
    "Julia",
    "Kotlin",
    "Kubernetes",
    "Lua",
    "Matlab",
    "MongoDB",
    "MySQL",
    "Next.js",
    "Node.js",
    "OCaml",
    "Objective-C",
    "OpenGL",
    "PHP",
    "Pascal",
    "Perl",
    "PostgreSQL",
    "PowerShell",
    "Prolog",
    "PyTorch",
    "Python",
    "R",
    "RESTful API",
    "React",
    "Redis",
    "Ruby",
    "Rust",
    "SOAP",
    "SQL",
    "SQLite",
    "Scala",
    "Scheme",
    "Shell",
    "Slack",
    "Smalltalk",
    "Spring",
    "Sublime Text",
    "Swift",
    "Tcl",
    "TensorFlow",
    "TypeScript",
    "Unity",
    "VBA",
    "Visual Basic",
    "Visual Studio Code",
    "Vue.js",
    "WebAssembly",
    "Wolfram Language",
    "XML",
    "XPath",
    "XQuery",
    "Xamarin",
    "Zig",
];

export const options = [
    "High School",
    "B. Tech.",
    "M. Tech.",
    "B. Eng.",
    "M. Eng.",
    "B. B. A.",
    "M. B. A.",
    "B. Sc.",
    "M. Sc.",
    "B. Com.",
    "M. Com.",
    "B. C. A.",
    "M. C. A.",
    "B. A.",
    "B. Ed.",
    "PhD",
    "Others",
];

export const tabs = [
    {
        label: "Personal",
        choice: 1,
    },
    {
        label: "Education",
        choice: 2,
    },
    {
        label: "Experience",
        choice: 3,
    },
    {
        label: "Projects",
        choice: 4,
    },
    {
        label: "Skills",
        choice: 5,
    },
    {
        label: "Certificates",
        choice: 6,
    },
    {
        label: "Links",
        choice: 7,
    },
];

export const scope = [
    {
        id: 1,
        label: "Hackathon",
    },
    {
        id: 2,
        label: "Personal",
    },
    {
        id: 3,
        label: "Open Source",
    },
    {
        id: 4,
        label: "Startup",
    },
];

export const signin = [
    {
        label: "Email Address*",
        type: "email",
        required: true,
    },
    {
        label: "Password*",
        type: "password",
        required: true,
    },
];

export const signup = [
    {
        label: "First Name*",
        type: "text",
        required: true,
    },
    {
        label: "Last Name",
        type: "text",
        required: false,
    },
    {
        label: "Date of Birth*",
        type: "date",
        required: true,
    },
    {
        label: "Email Address*",
        type: "email",
        required: true,
    },
    {
        label: "Password*",
        type: "password",
        required: true,
    },
    {
        label: "Gender*",
        type: "select",
        options: ["Male", "Female", "Others", "Prefer not to disclose"],
        required: true,
    },
    {
        label: "Country*",
        type: "select",
        options: countries,
        required: true,
    },
    {
        label: "Address*",
        type: "text",
        required: true,
    },
    {
        label: "Pincode*",
        type: "number",
        required: true,
    },
    {
        label: "College*",
        type: "text",
        required: true,
    },
    {
        label: "University*",
        type: "text",
        required: true,
    },
    {
        label: "University Roll*",
        type: "text",
        required: true,
    },
    {
        label: "Course*",
        type: "select",
        default: "Select Course",
        options: options,
        required: true,
    },
    {
        label: "Course Type*",
        type: "select",
        options: ["Full-Time", "Part-Time"],
        required: true,
    },
    {
        label: "Specialisation*",
        type: "text",
        required: true,
    },
    {
        label: "Course Duration (Years)*",
        type: "number",
        required: true,
    },
    {
        label: "Year of Graduation*",
        type: "number",
        required: true,
    },
    {
        label: "Course Status*",
        type: "select",
        options: ["Pursuing", "Completed"],
        required: true,
    },
];

export const account = [
    {
        label: "First Name",
        type: "text",
        required: true,
        field: "fname",
    },
    {
        label: "Last Name",
        type: "text",
        required: false,
        field: "lname",
    },
    {
        label: "Email Address",
        type: "text",
        required: true,
        field: "email",
    },
    {
        label: "Password",
        type: "password",
        required: true,
        field: "password",
    },
    {
        label: "Date of Birth",
        type: "date",
        required: true,
        field: "dob",
    },
    {
        label: "Gender",
        type: "select",
        required: true,
        options: ["Male", "Female", "Others", "Prefer not to disclose"],
        field: "gender",
    },
    {
        label: "Country",
        type: "select",
        required: true,
        options: countries,
        field: "country",
    },
    {
        label: "Address",
        type: "text",
        required: true,
        field: "address",
    },
    {
        label: "Pincode",
        type: "number",
        required: true,
        field: "pinCode",
    },
    {
        label: "College",
        type: "text",
        required: true,
        field: "college",
    },
    {
        label: "University",
        type: "text",
        required: true,
        field: "university",
    },
    {
        label: "University Roll",
        type: "text",
        required: true,
        field: "roll",
    },
    {
        label: "Course",
        type: "select",
        required: true,
        options: [
            "B. Tech.",
            "M. Tech.",
            "B. Eng.",
            "M. Eng.",
            "B. B. A.",
            "M. B. A.",
            "B. Sc.",
            "M. Sc.",
            "B. Com.",
            "M. Com.",
            "B. C. A.",
            "M. C. A.",
            "B. A.",
            "B. Ed.",
            "PhD",
            "Others",
        ],
        field: "course",
    },
    {
        label: "Course Type",
        type: "select",
        required: true,
        options: ["Full-Time", "Part-Time"],
        field: "type",
    },
    {
        label: "Specialisation",
        type: "text",
        required: true,
        field: "specialisation",
    },
    {
        label: "Course Duration (Years)",
        type: "number",
        required: true,
        field: "duration",
    },
    {
        label: "Year of Graduation",
        type: "number",
        required: true,
        field: "grad",
    },
    {
        label: "Course Status",
        type: "select",
        required: true,
        options: ["Pursuing", "Completed"],
        field: "status",
    },
];